### ISSUE TITLE
GitHub Dependency: prepare script ignored

### ISSUE THREAD

**Issue by dahlbyk** [codesandbox/dependency-packager#2]
I'm trying to use CodeSandbox to verify a fix by installing a dependency directly from a GitHub branch. I've traced the error back to this project:

> Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the dependency griddle-react@GriddleGriddle/Griddle#my-branch: ENOENT: no such file or directory, scandir '/tmp/1532470022/node_modules/griddle-react/dist/module'

The package's `prepare` script is not being executed, probably due to `--ignore-scripts`?

https://github.com/codesandbox-app/dependency-packager/blob/544b6357c8ac60f6bcb3084527015ade2dafe7a2/functions/packager/dependencies/install-dependencies.ts#L16

I'm wondering if `--ignore-scripts` is necessary, or perhaps should be avoided for Git/GitHub versions?

**Comment by CompuIves** [comment]
Hmm, we did the `ignore-scripts` because of security reasons, but since we're running on serverless functions nowadays I think it's safe to remove. I'll remove it now!

**Comment by CompuIves** [comment]
Live now!

**Comment by dahlbyk** [comment]
Hrm, still not working. Are you using a version of `yarn` that supports `prepare` for GitHub dependencies?

For reference, this is the sandbox I'm using to test: https://codesandbox.io/s/nkq0wrz1jl.

**Comment by CompuIves** [comment]
Ah, I'm sorry for that! I accidentally deployed to staging instead of prod. Deploying to prow now.
